In [ ]:
# ================================
# INSTALL (Run once if needed)
# ================================
# !pip install nltk scikit-learn gensim

import nltk
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
from gensim.models import Word2Vec
from nltk.tokenize import word_tokenize
import numpy as np

# Download tokenizer
nltk.download('punkt')
nltk.download('punkt_tab')


[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!


True

In [ ]:
# ================================
# DATASET
# ================================
corpus = [
    "This is a sample sentence",
    "This sentence is for testing",
    "Word embeddings are useful in NLP"
]


In [ ]:
# ================================
# 1. BAG OF WORDS (COUNT)
# ================================
print("\n--- BAG OF WORDS (COUNT) ---")

vectorizer = CountVectorizer()
X = vectorizer.fit_transform(corpus)

vocab = vectorizer.get_feature_names_out()
bow_matrix = X.toarray()

print("Vocabulary:", vocab)
print("BoW Matrix:\n", bow_matrix)


--- BAG OF WORDS (COUNT) ---
Vocabulary: ['are' 'embeddings' 'for' 'in' 'is' 'nlp' 'sample' 'sentence' 'testing'
 'this' 'useful' 'word']
BoW Matrix:
 [[0 0 0 0 1 0 1 1 0 1 0 0]
 [0 0 1 0 1 0 0 1 1 1 0 0]
 [1 1 0 1 0 1 0 0 0 0 1 1]]


In [ ]:
# ================================
# 2. NORMALIZED COUNT (TERM FREQUENCY)
# ================================
print("\n--- NORMALIZED COUNT ---")

normalized_bow = bow_matrix / bow_matrix.sum(axis=1, keepdims=True)

print("Normalized BoW:\n", normalized_bow)



--- NORMALIZED COUNT ---
Normalized BoW:
 [[0.         0.         0.         0.         0.25       0.
  0.25       0.25       0.         0.25       0.         0.        ]
 [0.         0.         0.2        0.         0.2        0.
  0.         0.2        0.2        0.2        0.         0.        ]
 [0.16666667 0.16666667 0.         0.16666667 0.         0.16666667
  0.         0.         0.         0.         0.16666667 0.16666667]]


In [ ]:
# ================================
# 3. TF-IDF
# ================================
print("\n--- TF-IDF ---")

tfidf = TfidfVectorizer()
tfidf_matrix = tfidf.fit_transform(corpus)

print("Vocabulary:", tfidf.get_feature_names_out())
print("TF-IDF Matrix:\n", tfidf_matrix.toarray())


--- TF-IDF ---
Vocabulary: ['are' 'embeddings' 'for' 'in' 'is' 'nlp' 'sample' 'sentence' 'testing'
 'this' 'useful' 'word']
TF-IDF Matrix:
 [[0.         0.         0.         0.         0.45985353 0.
  0.60465213 0.45985353 0.         0.45985353 0.         0.        ]
 [0.         0.         0.51741994 0.         0.3935112  0.
  0.         0.3935112  0.51741994 0.3935112  0.         0.        ]
 [0.40824829 0.40824829 0.         0.40824829 0.         0.40824829
  0.         0.         0.         0.         0.40824829 0.40824829]]


In [ ]:
# ================================
# 4. WORD2VEC EMBEDDINGS
# ================================
print("\n--- WORD2VEC ---")

# Tokenize sentences
tokenized_corpus = [word_tokenize(sentence.lower()) for sentence in corpus]

# Train Word2Vec model
model = Word2Vec(
    sentences=tokenized_corpus,
    vector_size=50,
    window=3,
    min_count=1,
    workers=4
)

# Example word vector
print("\nVector for 'sentence':")
print(model.wv['sentence'])

# Similar words
print("\nWords similar to 'sentence':")
print(model.wv.most_similar('sentence'))


--- WORD2VEC ---

Vector for 'sentence':
[-1.0724545e-03  4.7286271e-04  1.0206699e-02  1.8018546e-02
 -1.8605899e-02 -1.4233618e-02  1.2917745e-02  1.7945977e-02
 -1.0030856e-02 -7.5267432e-03  1.4761009e-02 -3.0669428e-03
 -9.0732267e-03  1.3108104e-02 -9.7203208e-03 -3.6320353e-03
  5.7531595e-03  1.9837476e-03 -1.6570430e-02 -1.8897636e-02
  1.4623532e-02  1.0140524e-02  1.3515387e-02  1.5257311e-03
  1.2701781e-02 -6.8107317e-03 -1.8928028e-03  1.1537147e-02
 -1.5043275e-02 -7.8722071e-03 -1.5023164e-02 -1.8600845e-03
  1.9076237e-02 -1.4638334e-02 -4.6675373e-03 -3.8754821e-03
  1.6154874e-02 -1.1861792e-02  9.0324880e-05 -9.5074680e-03
 -1.9207101e-02  1.0014586e-02 -1.7519170e-02 -8.7836506e-03
 -7.0199967e-05 -5.9236289e-04 -1.5322480e-02  1.9229487e-02
  9.9641159e-03  1.8466286e-02]

Words similar to 'sentence':
[('sample', 0.16704076528549194), ('embeddings', 0.13204392790794373), ('this', 0.1267007291316986), ('testing', 0.0998455360531807), ('is', 0.042373016476631165), 